# Configuration for chart-testing
chart-dirs:
  - helm-chart
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - istio=https://istio-release.storage.googleapis.com/charts
  - prometheus-community=https://prometheus-community.github.io/helm-charts
helm-extra-args: --timeout 600s
check-version-increment: true
validate-maintainers: false