# Values for deploying in a Kubeflow environment
# Use this with: helm install -f values-kubeflow.yaml

# Override config for Kubeflow
config:
  USERID_HEADER: "kubeflow-userid"
  APP_PREFIX: "/kserve-endpoints"
  GRAFANA_PREFIX: "/grafana"
  GRAFANA_CPU_MEMORY_DB: "db/knative-serving-revision-cpu-and-memory-usage"
  GRAFANA_HTTP_REQUESTS_DB: "db/knative-serving-revision-http-requests"

# Enable Istio and configure for Kubeflow
istio:
  enabled: true
  virtualService:
    gateways:
      - kubeflow/kubeflow-gateway
    hosts:
      - "*"
    uriPrefix: "/kserve-endpoints/"
    rewrite:
      enabled: true
      uri: "/"
  authorizationPolicy:
    enabled: true
    action: ALLOW
    rules:
      - from:
        - source:
            principals:
            - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account

# Inject Istio sidecar
podAnnotations:
  sidecar.istio.io/inject: "true"