{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kserve-models-web-app.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kserve-models-web-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kserve-models-web-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    {{- with .Values.networkPolicy.ingress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    - from: []
      ports:
        - protocol: TCP
          port: 5000
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- with .Values.networkPolicy.egress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS to Kubernetes API
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP/HTTPS for external dependencies
    - to: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    {{- end }}
  {{- end }}
{{- end }}